name: 'Control State of EC2 Instances'
description: 'Start/Stop EC2 Instances from withing GitHub Actions Workflows'
author: 'Hipcamp'
inputs:
  region:
    required: true
    description: 'selected region for EC2 instances'
  action:
    required: true
    description: 'stop or start'
  label:
    required: true
    description: 'the label to filter EC2 instances with'
  timeout:
    required: true
    description: 'time to wait for a matching instance (seconds)'
    default: '180'
  runners:
    required: true
    description: 'the amount of runners to start with matching labels'
    default: '1'
  token:
    required: true
    description: 'the gha token for getting idle status runners from github api'
outputs:
  ids:
    description: 'ids of the affected EC2 instances'
  label:
    description: 'the label used to start the runners'
  started:
    description: 'number of runners started by this action'
runs:
  using: 'node12'
  main: 'dist/index.js'
