name: 'Control State of EC2 Instances'
description: 'Start/Stop EC2 Instances from withing GitHub Actions Workflows'
author: 'Hipcamp'
inputs:
  region:
    required: true
    description: 'selected region for EC2 instances'
  action:
    required: true
    description: 'stop or start'
  label:
    required: false
    description: 'the label to filter EC2 instances with'
  instances:
    required: false
    description: 'a list of EC2 instance ids'
  timeout:
    required: true
    description: 'time to wait for a matching instance (seconds)'
    default: '60'
  runners:
    required: true
    description: 'the amount of runners to start with matching labels'
    default: '1'
  token:
    required: false
    description: 'temporary gha token for testing getting idle status runners from github api'
    default: 'token'
outputs:
  ids:
    description: 'ids of the affected EC2 instances'
runs:
  using: 'node12'
  main: 'dist/index.js'
