name: 'Control State of EC2 Instances'
description: 'Start/Stop EC2 Instances from withing GitHub Actions Workflows'
author: 'Hipcamp'
inputs:
  region:
    required: true
    description: 'selected region for EC2 instances'
  action:
    required: true
    description: 'stop or start'
  label:
    required: false
    description: 'the label to filter EC2 instances with'
  instance:
    required: false
    description: 'the EC2 instance id'
  timeout:
    required: true
    description: 'time to wait for a matching instance (seconds)'
    default: '60'
outputs:
  id:
    description: 'id of the affected EC2 instance'
runs:
  using: 'node12'
  main: 'dist/index.js'
