name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  region:
    required: true
    description: 'selected region for EC2 instances'
  action:
    required: true
    description: 'stop or start'
  label:
    required: false
    description: 'the label to filter EC2 instances with'
  instance:
    required: false
    description: 'the EC2 instance id'
outputs:
  id:
    description: 'id of the affected EC2 instance'
runs:
  using: 'node12'
  main: 'dist/index.js'
